language: csharp
script:
  - xbuild /p:Configuration=Debug WowDotNetAPI.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore WowDotNetAPI.sln
after_script:
  - nunit-console Explorers.Test/bin/Debug/WowDotNetAPI.Explorers.Test.dll